DROP DATABASE IF EXISTS ACADEMIA1;

CREATE DATABASE ACADEMIA1 CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

USE ACADEMIA1;

CREATE TABLE ENDERECO (
CEP CHAR(9) PRIMARY KEY,
RUA VARCHAR(60) NOT NULL,
BAIRRO VARCHAR(40) NOT NULL,
CIDADE VARCHAR(40) NOT NULL,
UF CHAR(2) NOT NULL);

CREATE TABLE ALUNO (
MATRICULA INTEGER PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(60) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
CPF CHAR(14) NOT NULL,
RG VARCHAR(15) NOT NULL,
DATANASCIMENTO DATE NOT NULL,
CEP CHAR(9) NOT NULL,
NUMEROCASA SMALLINT NOT NULL,
COMPLEMENTO VARCHAR(30),
FOTO VARCHAR(255),
FOREIGN KEY(CEP) REFERENCES ENDERECO(CEP));


CREATE TABLE FUNCIONARIO (
CPFFUNCIONARIO CHAR (14) PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
RG VARCHAR(15) NOT NULL,
CEP CHAR(9) NOT NULL,
NUMEROCASA SMALLINT NOT NULL,
COMPLEMENTO VARCHAR(30),
FOTO VARCHAR(255),
FOREIGN KEY(CEP) REFERENCES ENDERECO(CEP));

CREATE TABLE PROFESSOR(
IDPROFESSOR INTEGER PRIMARY KEY AUTO_INCREMENT,
DISPONIBILIDADE VARCHAR(40) NOT NULL,
CPFFUNCIONARIO CHAR(14) NOT NULL,
FOREIGN KEY(CPFFUNCIONARIO) REFERENCES FUNCIONARIO(CPFFUNCIONARIO));

CREATE TABLE ATIVIDADE(
IDATIVIDADE INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMEATIVIDADE VARCHAR(60) NOT NULL,
DESCRICAO VARCHAR(100) NOT NULL);

CREATE TABLE HABILITAPROFESSOR(
IDHABILITACAO INTEGER PRIMARY KEY AUTO_INCREMENT,
IDATIVIDADE INTEGER NOT NULL,
IDPROFESSOR INTEGER NOT NULL,
FOREIGN KEY (IDATIVIDADE) REFERENCES ATIVIDADE (IDATIVIDADE),
FOREIGN KEY (IDPROFESSOR) REFERENCES PROFESSOR (IDPROFESSOR));

CREATE TABLE AULA(
IDAULA INTEGER PRIMARY KEY AUTO_INCREMENT,
DATAAULA DATE NOT NULL,
HORARIO VARCHAR(30) NOT NULL,
IDPROFESSOR INTEGER NOT NULL,
IDATIVIDADE INTEGER NOT NULL,
FOREIGN KEY (IDPROFESSOR) REFERENCES PROFESSOR (IDPROFESSOR),
FOREIGN KEY (IDATIVIDADE) REFERENCES ATIVIDADE (IDATIVIDADE));

CREATE TABLE AULAALUNO (
IDAULAALUNO INTEGER PRIMARY KEY AUTO_INCREMENT,
IDAULA INTEGER NOT NULL,
MATRICULA INTEGER NOT NULL,
FOREIGN KEY (MATRICULA) REFERENCES ALUNO (MATRICULA),
FOREIGN KEY (IDAULA) REFERENCES AULA (IDAULA));

CREATE TABLE PRODUTO (
CODIGOPRODUTO INTEGER PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (60) NOT NULL,
COR VARCHAR (30) NOT NULL,
VALOR DOUBLE NOT NULL,
TAMANHO CHAR (2) NOT NULL,
QUANTIDADE INTEGER NOT NULL);

CREATE TABLE VENDA (
IDVENDA INTEGER PRIMARY KEY AUTO_INCREMENT,
CPFFUNCIONARIO CHAR (14) NOT NULL,
CODIGOPRODUTO INTEGER NOT NULL,
QUANTIDADE INTEGER NOT NULL,
VALORVENDA DOUBLE NOT NULL,
DATA DATE NOT NULL,
FOREIGN KEY (CPFFUNCIONARIO) REFERENCES FUNCIONARIO (CPFFUNCIONARIO),
FOREIGN KEY (CODIGOPRODUTO) REFERENCES PRODUTO (CODIGOPRODUTO));

INSERT INTO ENDERECO
(CEP,RUA,BAIRRO,CIDADE,UF)

VALUES
('23040-550','ESTRADA DO MOINHO','CAMPO GRANDE','RIO DE JANEIRO','RJ'),
('21775-430','RUA CERIBA','PADRE MIGUEL','RIO DE JANEIRO','RJ');

INSERT INTO ALUNO
(NOME,TELEFONE,CPF,RG,DATANASCIMENTO,CEP,NUMEROCASA,COMPLEMENTO,FOTO)

VALUES
('CARAMELO OLIVEIRA DE MATTOS QUINTANILHA','2199036-7137','145.585.787-09','25.325.255-08','2020/12/14','23040-550','2355','BLOCO6 APTO 506'),
('PRETINHO OLIVEIRA DE MATTOS QUINTANILHA','2199036-7137','145.875.987-09','25.625.805-06','2013/01/01','21775-430','325','CASA 2');